"""DodaniePolaPolskieStreszczenie

Revision ID: d5622edb8f6c
Revises: def8dfc107f7
Create Date: 2025-10-27 19:50:17.997786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5622edb8f6c'
down_revision: Union[str, Sequence[str], None] = 'def8dfc107f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ksiazki', sa.Column('polski_tytul', sa.String(length=500), nullable=True))
    op.add_column('ksiazki', sa.Column('polskie_streszczenie', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ksiazki', 'polskie_streszczenie')
    op.drop_column('ksiazki', 'polski_tytul')
    # ### end Alembic commands ###
