"""DodanieModeluKsiazka

Revision ID: def8dfc107f7
Revises: 
Create Date: 2025-10-27 19:27:00.744404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'def8dfc107f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ksiazki',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('angielski_tytul', sa.String(length=500), nullable=False),
    sa.Column('angielskie_streszczenie', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ksiazki')
    # ### end Alembic commands ###
